In [149]:
from pathlib import Path
import pandas as pd
from pypdf import PdfReader
import time
import re
import unicodedata
from transformers import AutoTokenizer
import numpy as np

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import DoclingDocument
from docling_core.types.doc import DocItemLabel,TableItem, TextItem
from docling_core.types.doc import ContentLayer

# 1.import des données et setup

In [3]:
RACINE = Path.cwd().parent          # notebooks/ -> racine du repo
DOSSIER_DATA = RACINE / "data"      # gitignored
PDF_REGLES = DOSSIER_DATA / "core-rules" / "fr-warhammer40k_regles_de_base_01_06_2026.pdf"   # à adapter
DOSSIER_SORTIE = DOSSIER_DATA / "interim"
DOSSIER_SORTIE.mkdir(parents=True, exist_ok=True)

assert PDF_REGLES.exists(), f"PDF introuvable : {PDF_REGLES}"

vérifier que le texte est bien sélectionnable

In [4]:
lecteur = PdfReader(PDF_REGLES)
nb_car = [len(p.extract_text() or "") for p in lecteur.pages]
stats = pd.Series(nb_car, index=range(1, len(nb_car) + 1), name="nb_caracteres")

print(f"{len(stats)} pages")
print(stats.describe())
print("Pages quasi vides (< 50 car.) :", stats[stats < 50].index.tolist())

88 pages
count      88.000000
mean     1853.977273
std      1098.675169
min         0.000000
25%       974.250000
50%      2127.000000
75%      2757.000000
max      4008.000000
Name: nb_caracteres, dtype: float64
Pages quasi vides (< 50 car.) : [3, 6, 7, 26, 27, 44, 45, 59, 60, 61, 75, 76, 77]

On vérifie s'il est possible de lire les signets. ça serait très utile  pour le découpage en chapitres.

In [5]:
def parcourir_signets(signets, lecteur, niveau=0):
    """Aplatit l'arbre des signets du PDF.

    Args:
        signets: liste (imbriquée) renvoyée par PdfReader.outline.
        lecteur: le PdfReader, pour résoudre les numéros de page.
        niveau: profondeur courante dans l'arbre.

    Yields:
        dict avec titre, niveau et page (numérotée à partir de 1).
    """
    for entree in signets:
        if isinstance(entree, list):   # une liste = les enfants du signet précédent
            yield from parcourir_signets(entree, lecteur, niveau + 1)
        else:
            yield {
                "titre": entree.title,
                "niveau": niveau,
                "page": lecteur.get_destination_page_number(entree) + 1,
            }

df_signets = pd.DataFrame(parcourir_signets(lecteur.outline, lecteur))
print(f"{len(df_signets)} signets, niveaux : {sorted(df_signets['niveau'].unique()) if len(df_signets) else '—'}")
df_signets.head(40)

0 signets, niveaux : —

Empty DataFrame
Columns: []
Index: []

# 2. conversion via docling

conversion Docling, mise en cache

In [12]:
options = PdfPipelineOptions(do_ocr=False, do_table_structure=True)
convertisseur = DocumentConverter(
    format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=options)}
)

debut = time.perf_counter()
resultat = convertisseur.convert(PDF_REGLES)  # , page_range=(1, 20) pour un test rapide
doc = resultat.document
print(f"Conversion : {time.perf_counter() - debut:.0f} s — statut {resultat.status}")

NOM_JSON_REGLES = "fr-warhammer40k_regles_de_base_docling.json"

CACHE_JSON = DOSSIER_SORTIE / NOM_JSON_REGLES
doc.save_as_json(CACHE_JSON)
(DOSSIER_SORTIE / "regles_docling.md").write_text(doc.export_to_markdown(), encoding="utf-8")

Loading weights: 100%|██████████| 770/770 [00:00<00:00, 16859.46it/s]

Conversion : 4 s — statut ConversionStatus.SUCCESS

152326

Pour les sessions suivantes, on recharge le cache au lieu de reconvertir :

In [7]:
doc = DoclingDocument.load_from_json(CACHE_JSON)

titres détectés par Docling, avec leur page.

In [13]:
for item, _ in doc.iterate_items():
    print(item.text)
    print("============")
    print(item.label.value)
    print("======================")
    print(getattr(item, "level", None))
    break

Dans les ténèbres d'un lointain futur, l'Humanité est au bord de l'extinction. L'Imperium à l'envergure galactique, assailli de toute part par des xénos voraces, des traîtres infâmes et des démons du Warp, compte une fois encore sur ses plus grands héros pour repousser l'obscurité qui menace de l'engloutir.
============
text
======================
None

In [14]:
titres = [
    {
        "texte": item.text,
        "label": item.label.value,
        "niveau_docling": getattr(item, "level", None),
        "page": item.prov[0].page_no if item.prov else None,
    }
    for item, _ in doc.iterate_items()
    if item.label in (DocItemLabel.TITLE, DocItemLabel.SECTION_HEADER)
]
df_titres = pd.DataFrame(titres)
print(df_titres["niveau_docling"].value_counts(dropna=False))
df_titres.head(40)

niveau_docling
1    298
Name: count, dtype: int64

,texte,label,niveau_docling,page
0,INTRODUCTION,section_header,1,4
1,"WARHAMMER 40,000 : L'APPLI",section_header,1,5
2,►Exemple de Référence d'Appli,section_header,1,5
3,RÈGLES ÉLÉMENTAIRES,section_header,1,7
4,ARMÉES 01.01,section_header,1,8
5,UNITÉS ET FIGURINES 01.02,section_header,1,8
6,JOUEUR ACTIF ET  JOUEUR ADVERSE 01.03,section_header,1,8
7,MESURER LES DISTANCES 01.04,section_header,1,9
8,DÉS 01.05,section_header,1,9
9,JETS DE COMMANDEMENT 01.06,section_header,1,9
10,JETS D'ÉBRANLEMENT 01.07,section_header,1,9
11,Tant qu'une unité est ébranlée :,section_header,1,9
12,MORAL SUR LE CHAMP DE BATAILLE,section_header,1,9
13,1. NOM DE LA FICHE TECHNIQUE 02.01,section_header,1,10
14,2. PROFILS 02.02,section_header,1,10
15,Sauvegarde Invulnérable (SvIn) :,section_header,1,10
16,3. APTITUDES 02.03,section_header,1,10
17,4. ARMES 02.04,section_header,1,10
18,5. MOTS-CLÉS 02.05,section_header,1,10
19,6. COMPOSITION D'UNITÉ ET AUTRES RÈGLES 02.06,section_header,1,11
20,7. OPTIONS D'ÉQUIPEMENT 02.07,section_header,1,11
21,VOIR AUSSI,section_header,1,11
22,PROFILS ET ARMES,section_header,1,11
23,APTITUDES,section_header,1,11
24,MOTS-CLÉS,section_header,1,11
25,DÉPLACER DES UNITÉS 03.01,section_header,1,12
26,DÉPLACER UNE FIGURINE EN LIGNE DROITE,section_header,1,12
27,FAIRE PIVOTER UNE FIGURINE,section_header,1,12
28,FINIR UN MOUVEMENT,section_header,1,12
29,VOIR AUSSI,section_header,1,13
30,TYPES DE MOUVEMENT,section_header,1,13
31,SI VOUS NE POUVEZ  PAS PLACER UNE UNITÉ,section_header,1,14
32,QU'EST-CE QUE LA COHÉSION ?,section_header,1,14
33,QU'EST-CE QUE L'ENGAGEMENT ?,section_header,1,14
34,PLACEMENT 03.02,section_header,1,14
35,COHÉSION 03.03,section_header,1,14
36,RECOUVRER SA COHÉSION,section_header,1,14
37,ENGAGEMENT 03.04,section_header,1,14
38,1. CHOISIR LES ARMES 04.01,section_header,1,16
39,EN TIRANT,section_header,1,16

# 3. chunking maison

## 3.1 découpage en chapitres, sections etc..

In [52]:
STRUCTURE_LIVRE = [
    {"titre":"INTRODUCTION", "page_debut" : 4,"page_fin":5,"sections": [
        {"num":"00","titre":"introduction", "page_debut": 4}

    ]},
    {"titre": "RÈGLES ÉLÉMENTAIRES", "page_debut": 6, "page_fin": 25, "sections": [
        {"num": "01", "titre": "Concepts de base", "page_debut": 8},
        {"num": "02", "titre": "Fiches techniques", "page_debut": 10},
        {"num": "03", "titre": "Mouvement", "page_debut": 12},
        {"num": "04", "titre": "Effectuer des attaques", "page_debut": 16},
        {"num": "05", "titre": "Séquence d'attaque", "page_debut": 18},
        {"num": "06", "titre": "Autres concepts", "page_debut": 24},
    ]},
    {"titre": "LE ROUND DE BATAILLE", "page_debut": 26, "page_fin": 43, "sections": [
        {"num": "07", "titre": "Le round de bataille", "page_debut": 28},
        {"num": "08", "titre": "Phase de commandement", "page_debut": 30},
        {"num": "09", "titre": "Phase de mouvement", "page_debut": 32},
        {"num": "10", "titre": "Phase de tir", "page_debut": 34},
        {"num": "11", "titre": "Phase de charge", "page_debut": 36},
        {"num": "12", "titre": "Phase de combat", "page_debut": 38},
    ]},
    {"titre": "CHAMPS DE BATAILLE ET TACTIQUES", "page_debut": 44, "page_fin": 59, "sections": [
        {"num": "13", "titre": "Terrain", "page_debut": 46},
        {"num": "14", "titre": "Objectif", "page_debut": 52},
        {"num": "15", "titre": "Stratagèmes", "page_debut": 54},
        {"num": "16", "titre": "Actions", "page_debut": 58},
    ]},
    {"titre": "RÈGLES AVANCÉES", "page_debut": 60, "page_fin": 75, "sections": [
        {"num": "17", "titre": "Monstres et véhicules", "page_debut": 62},
        {"num": "18", "titre": "Transport", "page_debut": 64},
        {"num": "19", "titre": "Unités attachées", "page_debut": 66},
        {"num": "20", "titre": "Réserves stratégiques", "page_debut": 68},
        {"num": "21", "titre": "Vol et élan", "page_debut": 70},
        {"num": "22", "titre": "Autres règles et aptitudes", "page_debut": 72},
        {"num": "23", "titre": "Aérodynes", "page_debut": 74},
    ]},
    {"titre": "RÉFÉRENCES", "page_debut": 76, "page_fin": 89, "sections": [
        {"num": "24", "titre": "Aptitudes de base", "page_debut": 78},
        {"num": None, "titre": "Appendices des règles", "page_debut": 86},
        {"num": None, "titre": "Index des règles de base", "page_debut": 89},
    ]},
]

fonctions de localisation et de classement des titres

In [115]:
MOTIF_CODE = re.compile(
    r"^(?:\d+\.\s+)?(?P<titre>.+?)\s+(?P<sec>\d{2})\.(?P<sous>\d{2})"
    r"(?:\s+(?P<cout>\d+\s*PC))?$"   # coût de stratagème facultatif, ex. « 1PC »
)


def inspecter_page(page: int, motif: str | None = None) -> None:
    """Affiche tout ce que Docling a produit sur une page, images et toutes couches comprises.

    Args:
        page: numéro de page à inspecter.
        motif: texte à rechercher dans la couche texte brute du PDF (ex. "10.04").
    """
    if motif:
        brut = lecteur.pages[page - 1].extract_text()
        pos = brut.find(motif)
        print(f"pypdf — '{motif}' {'trouvé' if pos >= 0 else 'ABSENT'} :",
              repr(brut[max(0, pos - 60): pos + 60]) if pos >= 0 else "")
    print(f"\n{'type':<18}{'label':<16}{'couche':<11}{'parent':<16}texte")
    for item, _ in doc.iterate_items(traverse_pictures=True,
                                     included_content_layers=set(ContentLayer),
                                     page_no=page):
        if isinstance(item, TableItem):
            texte = item.export_to_markdown(doc=doc)
        else:
            texte = getattr(item, "text", "")
        parent = item.parent.cref if item.parent else "-"
        print(f"{type(item).__name__:<18}{item.label.value:<16}"
              f"{item.content_layer.value:<11}{parent:<16}{texte[:70]!r}")

def preparer_titre(texte: str) -> str:
    """Rend un titre comparable : NFKC, sans caractères de format invisibles, espaces simples.

    Args:
        texte: texte brut du titre.

    Returns:
        Titre nettoyé des artefacts d'encodage (utilisé pour la détection et comme métadonnée).
    """
    t = unicodedata.normalize("NFKC", texte)
    t = "".join(c for c in t if c.isspace() or unicodedata.category(c) not in ("Cc", "Cf"))
    return re.sub(r"\s+", " ", t).strip()

def normaliser(texte: str) -> str:
    """Forme de comparaison : sans accents, minuscules, espaces simples."""
    t = unicodedata.normalize("NFKD", preparer_titre(texte))
    t = "".join(c for c in t if not unicodedata.combining(c))
    return t.casefold()

def analyser_titre(texte: str, section_num: str | None = None) -> dict:
    """Classe un titre détecté par Docling.

    Args:
        texte: texte brut du titre.
        section_num: section déduite de la page, pour écarter les renvois.

    Returns:
        dict avec type (sous_section | renvoi_suspect | pseudo_titre | titre_chapitre
        | titre_section | sous_partie), titre et code.
    """
    t = preparer_titre(texte)
    if m := MOTIF_CODE.match(t):
        code = f"{m['sec']}.{m['sous']}"
        if section_num is not None and m["sec"] != section_num:
            return {"type": "renvoi_suspect", "titre": t, "code": code}
        return {"type": "sous_section", "titre": m["titre"], "code": code}
    if t.endswith(":"):
        return {"type": "pseudo_titre", "titre": t, "code": None}
    n = re.sub(r"^\d+\s*", "", normaliser(t))
    if n in TITRES_CHAPITRES:
        return {"type": "titre_chapitre", "titre": t, "code": None}
    if n in TITRES_SECTIONS:
        return {"type": "titre_section", "titre": t, "code": None}
    return {"type": "sous_partie", "titre": t, "code": None}


TITRES_CHAPITRES = {normaliser(c["titre"]) for c in STRUCTURE_LIVRE}
TITRES_SECTIONS = {normaliser(s["titre"]) for c in STRUCTURE_LIVRE for s in c["sections"]}

def localiser(page: int | None) -> dict:
    """Déduit chapitre et section à partir du numéro de page.

    Args:
        page: numéro de page Docling (1-indexé), ou None.

    Returns:
        dict avec chapitre, section_num et section_titre.
    """
    vide = {"chapitre": None, "section_num": None, "section_titre": None}
    if page is None:
        return vide
    chapitre = next((c for c in STRUCTURE_LIVRE if c["page_debut"] <= page <= c["page_fin"]), None)
    if chapitre is None:
        nom = "LIMINAIRE" if page < STRUCTURE_LIVRE[0]["page_debut"] else "HORS SOMMAIRE"
        return {**vide, "chapitre": nom}
    candidates = [s for s in chapitre["sections"] if s["page_debut"] <= page]
    if not candidates:  # pages d'ouverture du chapitre, avant sa première section
        return {**vide, "chapitre": chapitre["titre"], "section_titre": "(ouverture de chapitre)"}
    section = candidates[-1]
    return {"chapitre": chapitre["titre"], "section_num": section["num"], "section_titre": section["titre"]}

def est_dans_image(item, doc) -> bool:
    """Indique si un élément est rattaché (directement ou non) à une image Docling.

    Args:
        item: élément Docling.
        doc: le DoclingDocument, pour remonter la chaîne des parents.

    Returns:
        True si un ancêtre de l'élément est une image.
    """
    parent = item.parent
    while parent is not None:
        if parent.cref.startswith("#/pictures"):
            return True
        parent = parent.resolve(doc).parent
    return False

construction du tableau à plat

In [105]:
LABELS_TITRE = (DocItemLabel.TITLE, DocItemLabel.SECTION_HEADER)

lignes, reperes = [], []  # reperes = titres structurels, gardés pour les diagnostics
etat = {"code": None, "sous_section": None, "sous_partie": None}
section_courante = None

for ordre, (item, _) in enumerate(doc.iterate_items(traverse_pictures=True)):
    if not isinstance(item, (TextItem, TableItem)):
        continue  # images, groupes : ignorés pour ce test

    page = item.prov[0].page_no if item.prov else None
    loc = localiser(page)

    # Changement de section (déduit de la page) -> on repart d'un état vierge
    cle_section = (loc["chapitre"], loc["section_titre"])
    if cle_section != section_courante:
        section_courante = cle_section
        etat = dict.fromkeys(etat)

    type_contenu = "table" if isinstance(item, TableItem) else item.label.value

    if isinstance(item, TextItem) and item.label in LABELS_TITRE:
        a = analyser_titre(item.text, loc["section_num"])
        if a["type"] != "pseudo_titre":
            reperes.append({"ordre": ordre, "page": page, **a, "section_num_page": loc["section_num"]})
        if a["type"] == "sous_section":
            etat = {"code": a["code"], "sous_section": a["titre"], "sous_partie": None}
            continue
        if a["type"] in ("sous_partie", "renvoi_suspect"):  # un renvoi reste une simple sous-partie
            etat["sous_partie"] = a["titre"]
            continue
        if a["type"] in ("titre_chapitre", "titre_section"):
            continue
        type_contenu = "pseudo_titre"  # gardé comme contenu ordinaire

    texte = item.export_to_markdown(doc=doc) if isinstance(item, TableItem) else item.text
    lignes.append({"ordre": ordre, **loc, **etat, "page": page,
                   "type_contenu": type_contenu,
                   "dans_image": est_dans_image(item, doc),
                   "texte": texte})

df_items = pd.DataFrame(lignes)
df_reperes = pd.DataFrame(reperes)
print(f"{len(df_items)} éléments de contenu, {len(df_reperes)} titres structurels")
df_items.head(20)

1321 éléments de contenu, 319 titres structurels

,ordre,chapitre,section_num,section_titre,code,sous_section,sous_partie,page,type_contenu,dans_image,texte
0,0,LIMINAIRE,NaN,NaN,NaN,NaN,NaN,1,text,False,"Dans les ténèbres d'un lointain futur, l'Human..."
1,1,LIMINAIRE,NaN,NaN,NaN,NaN,NaN,1,text,False,Il n'y a pas de paix. Pas de répit. Pas de par...
2,2,LIMINAIRE,NaN,NaN,NaN,NaN,NaN,2,table,False,| Chaque section et sous-section possède ici u...
3,4,INTRODUCTION,00,introduction,NaN,NaN,NaN,4,text,False,Bienvenue dans les Règles de Base de Warhammer...
4,5,INTRODUCTION,00,introduction,NaN,NaN,NaN,4,text,False,"Warhammer 40,000 est un jeu de bataille sur ta..."
5,6,INTRODUCTION,00,introduction,NaN,NaN,NaN,4,text,False,Une bataille dure en général cinq rounds à l'i...
6,7,INTRODUCTION,00,introduction,NaN,NaN,NaN,5,text,False,"Chaque partie de Warhammer 40,000 s'inscrit da..."
7,8,INTRODUCTION,00,introduction,NaN,NaN,NaN,5,text,False,Les missions demanderont aux joueurs de rassem...
8,9,INTRODUCTION,00,introduction,NaN,NaN,NaN,5,text,False,Quelle que soit la faction que vous souhaitez ...
9,10,INTRODUCTION,00,introduction,NaN,NaN,NaN,5,text,False,"Enfin, avant de disputer une partie de Warhamm..."
10,11,INTRODUCTION,00,introduction,NaN,NaN,NaN,5,text,False,Les pages suivantes contiennent les Règles de ...
11,14,INTRODUCTION,00,introduction,NaN,NaN,"WARHAMMER 40,000 : L'APPLI",5,text,False,"L'appli Warhammer 40,000 est le compagnon idéa..."
12,15,INTRODUCTION,00,introduction,NaN,NaN,"WARHAMMER 40,000 : L'APPLI",5,text,False,"L'appli Warhammer 40,000 est par ailleurs le m..."
13,16,INTRODUCTION,00,introduction,NaN,NaN,"WARHAMMER 40,000 : L'APPLI",5,text,False,"Sur les pages suivantes, les renvois au conten..."
14,18,INTRODUCTION,00,introduction,NaN,NaN,►Exemple de Référence d'Appli,5,text,False,Scannez le code ci-dessous pour installer dès ...
15,21,INTRODUCTION,00,introduction,NaN,NaN,►Exemple de Référence d'Appli,5,text,False,5
16,22,RÈGLES ÉLÉMENTAIRES,NaN,(ouverture de chapitre),NaN,NaN,NaN,6,text,False,6
17,25,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,NaN,NaN,NaN,8,text,False,01
18,26,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,NaN,NaN,NaN,8,text,False,Avant d'apprendre à déplacer vos guerriers sur...
19,28,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,01.01,ARMÉES,NaN,8,text,False,"Chaque joueur d'une partie de Warhammer 40,000..."

In [106]:
df_reperes

,ordre,page,type,titre,code,section_num_page
0,3,4,titre_chapitre,INTRODUCTION,NaN,00
1,13,5,sous_partie,"WARHAMMER 40,000 : L'APPLI",NaN,00
2,17,5,sous_partie,►Exemple de Référence d'Appli,NaN,00
3,24,7,titre_chapitre,RÈGLES ÉLÉMENTAIRES,NaN,NaN
4,27,8,sous_section,ARMÉES,01.01,01
...,...,...,...,...,...,...
314,1758,87,sous_partie,VOIR AUSSI,NaN,NaN
315,1759,87,sous_partie,EFFECTIF INITIAL ET DEMI-EFFECTIF,NaN,NaN
316,1766,88,sous_partie,OBJECTIFS N'ÉTANT PAS DANS UNE ZONE DE TERRAIN,NaN,NaN
317,1769,88,sous_partie,RESSUSCITÉ,NaN,NaN
318,1775,88,sous_partie,FAQ,NaN,NaN

### diagnostics

In [107]:
# 1. Vue d'ensemble : taille et étendue de chaque section
resume = (
    df_items.groupby(["chapitre", "section_num", "section_titre"], dropna=False, sort=False)
    .agg(nb_elements=("texte", "size"),
         nb_caracteres=("texte", lambda s: s.str.len().sum()),
         page_min=("page", "min"), page_max=("page", "max"),
         nb_codes=("code", "nunique"))
)
display(resume)

                                                                        nb_elements  \
chapitre                        section_num section_titre
LIMINAIRE                       NaN         NaN                                   3
INTRODUCTION                    00          introduction                         13
RÈGLES ÉLÉMENTAIRES             NaN         (ouverture de chapitre)               1
                                01          Concepts de base                     42
                                02          Fiches techniques                   110
                                03          Mouvement                            96
                                04          Effectuer des attaques               41
                                05          Séquence d'attaque                  123
                                06          Autres concepts                      17
LE ROUND DE BATAILLE            07          Le round de bataille                 22
                                08          Phase de commandement                28
                                09          Phase de mouvement                   57
                                10          Phase de tir                         52
                                11          Phase de charge                      41
                                12          Phase de combat                      92
CHAMPS DE BATAILLE ET TACTIQUES 13          Terrain                              88
                                14          Objectif                             17
                                15          Stratagèmes                         125
                                16          Actions                              31
RÈGLES AVANCÉES                 NaN         (ouverture de chapitre)               1
                                17          Monstres et véhicules                19
                                18          Transport                            41
                                19          Unités attachées                     18
                                20          Réserves stratégiques                24
                                21          Vol et élan                          36
                                22          Autres règles et aptitudes           16
                                23          Aérodynes                            11
RÉFÉRENCES                      24          Aptitudes de base                   122
                                NaN         Appendices des règles                34

                                                                        nb_caracteres  \
chapitre                        section_num section_titre
LIMINAIRE                       NaN         NaN                                  8999
INTRODUCTION                    00          introduction                         3569
RÈGLES ÉLÉMENTAIRES             NaN         (ouverture de chapitre)                 1
                                01          Concepts de base                     4818
                                02          Fiches techniques                    5195
                                03          Mouvement                            6642
                                04          Effectuer des attaques               4333
                                05          Séquence d'attaque                  11506
                                06          Autres concepts                      3197
LE ROUND DE BATAILLE            07          Le round de bataille                 2335
                                08          Phase de commandement                2714
                                09          Phase de mouvement                   4542
                                10          Phase de tir                         4228
                                11          Phase de charge                      3797
                                12          Phase de combat                      9888
CHAMPS DE BATAILLE ET TACTIQUES 13          Terrain                             11073
                                14          Objectif                             3311
                                15          Stratagèmes                          9133
                                16          Actions                              2175
RÈGLES AVANCÉES                 NaN         (ouverture de chapitre)                 2
                                17          Monstres et véhicules                3012
                                18          Transport                            4679
                                19          Unités attachées                     5167
                                20          Réserves stratégiques                3581
                                21          Vol et élan                          3100
                                22          Autres règles et aptitudes           2902
                                23          Aérodynes                            1715
RÉFÉRENCES                      24          Aptitudes de base                   19979
                                NaN         Appendices des règles                8974

                                                                        page_min  \
chapitre                        section_num section_titre
LIMINAIRE                       NaN         NaN                                1
INTRODUCTION                    00          introduction                       4
RÈGLES ÉLÉMENTAIRES             NaN         (ouverture de chapitre)            6
                                01          Concepts de base                   8
                                02          Fiches techniques                 10
                                03          Mouvement                         12
                                04          Effectuer des attaques            16
                                05          Séquence d'attaque                18
                                06          Autres concepts                   24
LE ROUND DE BATAILLE            07          Le round de bataille              28
                                08          Phase de commandement             30
                                09          Phase de mouvement                32
                                10          Phase de tir                      34
                                11          Phase de charge                   36
                                12          Phase de combat                   38
CHAMPS DE BATAILLE ET TACTIQUES 13          Terrain                           46
                                14          Objectif                          52
                                15          Stratagèmes                       54
                                16          Actions                           58
RÈGLES AVANCÉES                 NaN         (ouverture de chapitre)           60
                                17          Monstres et véhicules             62
                                18          Transport                         64
                                19          Unités attachées                  66
                                20          Réserves stratégiques             68
                                21          Vol et élan                       70
                                22          Autres règles et aptitudes        72
                                23          Aérodynes                         74
RÉFÉRENCES                      24          Aptitudes de base                 78
                                NaN         Appendices des règles             86

                                                                        page_max  \
chapitre                        section_num section_titre
LIMINAIRE                       NaN         NaN                                2
INTRODUCTION                    00          introduction                       5
RÈGLES ÉLÉMENTAIRES             NaN         (ouverture de chapitre)            6
                                01          Concepts de base                   9
                                02          Fiches techniques                 11
                                03          Mouvement                         15
                                04          Effectuer des attaques            17
                                05          Séquence d'attaque                23
                                06          Autres concepts                   25
LE ROUND DE BATAILLE            07          Le round de bataille              29
                                08          Phase de commandement             31
                                09          Phase de mouvement                33
                                10          Phase de tir                      35
                                11          Phase de charge                   37
                                12          Phase de combat                   43
CHAMPS DE BATAILLE ET TACTIQUES 13          Terrain                           51
                                14          Objectif                          53
                                15          Stratagèmes                       57
                                16          Actions                           58
RÈGLES AVANCÉES                 NaN         (ouverture de chapitre)           60
                                17          Monstres et véhicules             63
                                18          Transport                         65
                                19          Unités attachées                  67
                                20          Réserves stratégiques             69
                                21          Vol et élan                       71
                                22          Autres règles et aptitudes        73
                                23          Aérodynes                         74
RÉFÉRENCES                      24          Aptitudes de base                 85
                                NaN         Appendices des règles             88

                                                                        nb_codes
chapitre                        section_num section_titre
LIMINAIRE                       NaN         NaN                                0
INTRODUCTION                    00          introduction                       0
RÈGLES ÉLÉMENTAIRES             NaN         (ouverture de chapitre)            0
                                01          Concepts de base                   7
                                02          Fiches techniques                  7
                                03          Mouvement                          4
                                04          Effectuer des attaques             3
                                05          Séquence d'attaque                 4
                                06          Autres concepts                    3
LE ROUND DE BATAILLE            07          Le round de bataille               3
                                08          Phase de commandement              5
                                09          Phase de mouvement                 7
                                10          Phase de tir                       7
                                11          Phase de charge                    4
                                12          Phase de combat                    9
CHAMPS DE BATAILLE ET TACTIQUES 13          Terrain                           11
                                14          Objectif                           3
                                15          Stratagèmes                       12
                                16          Actions                            1
RÈGLES AVANCÉES                 NaN         (ouverture de chapitre)            0
                                17          Monstres et véhicules              3
                                18          Transport                          5
                                19          Unités attachées                   4
                                20          Réserves stratégiques              4
                                21          Vol et élan                        3
                                22          Autres règles et aptitudes         5
                                23          Aérodynes                          4
RÉFÉRENCES                      24          Aptitudes de base                 38
                                NaN         Appendices des règles              0

In [111]:
# 2. Cohérence code / page : le préfixe du code doit égaler la section déduite de la page
codes = df_reperes[df_reperes["type"] == "sous_section"]
incoherents = codes[codes["code"].str[:2] != codes["section_num_page"]]
print(f"\n⚠️ {len(incoherents)} code(s) incohérent(s) avec la page")
display(incoherents[["code", "titre", "page", "section_num_page"]])

⚠️ 0 code(s) incohérent(s) avec la page

Empty DataFrame
Columns: [code, titre, page, section_num_page]
Index: []

In [112]:
# 3. Continuité et doublons des codes
for sec, g in codes.groupby(codes["code"].str[:2]):
    nums = sorted({int(c[3:]) for c in g["code"]})
    manquants = sorted(set(range(1, max(nums) + 1)) - set(nums))
    if manquants:
        print(f"⚠️ Section {sec} : sous-sections absentes {manquants}")
doublons = codes["code"].value_counts()
print("Codes en double :", doublons[doublons > 1].to_dict())

Codes en double : {'15.11': 2}

In [113]:
# 4. Décalage de pages : le 1er code de chaque section tombe-t-il sur sa page de début ?
attendu = {s["num"]: s["page_debut"] for c in STRUCTURE_LIVRE for s in c["sections"] if s["num"]}
premiere_page = codes.groupby(codes["code"].str[:2])["page"].min()
ecarts = {sec: (int(p), attendu.get(sec)) for sec, p in premiere_page.items() if p != attendu.get(sec)}
print("\nSections dont le 1er code n'est pas sur la page attendue (trouvée, attendue) :", ecarts)

# 5. Titres de chapitre / section détectés par Docling (contrôle croisé)
display(df_reperes[df_reperes["type"].isin(["titre_chapitre", "titre_section"])][["type", "titre", "page"]])

Sections dont le 1er code n'est pas sur la page attendue (trouvée, attendue) : {}

               type                            titre  page
0    titre_chapitre                     INTRODUCTION     4
3    titre_chapitre              RÈGLES ÉLÉMENTAIRES     7
70    titre_section           EFFECTUER DES ATTAQUES    20
98   titre_chapitre             LE ROUND DE BATAILLE    27
103   titre_section            PHASE DE COMMANDEMENT    29
104   titre_section               PHASE DE MOUVEMENT    29
105   titre_section                     PHASE DE TIR    29
106   titre_section                  PHASE DE CHARGE    29
107   titre_section                  PHASE DE COMBAT    29
167  titre_chapitre  CHAMPS DE BATAILLE ET TACTIQUES    45
222  titre_chapitre                  RÈGLES AVANCÉES    61
266  titre_chapitre                       RÉFÉRENCES    77

In [ ]:
mask = (df_items["chapitre"]=="CHAMPS DE BATAILLE ET TACTIQUES")  & (df_items["section_num"]=="15") & (df_items["code"]=="15.01")
df_items[mask]

In [103]:
inspecter_page(56, motif="15.02")

pypdf — '15.02' trouvé : 'RELANCE DE COMMANDEMENT 15.02 1PC\nSTRATAGÈME DE BASE\nUn grand commandant peut même p'

type              label           couche     parent          texte
SectionHeaderItem section_header  body       #/body          'RELANCE DE COMMANDEMENT 15.02 1PC'
SectionHeaderItem section_header  body       #/body          'STRATAGÈME DE BASE'
TextItem          text            body       #/body          'Un grand commandant peut même plier les caprices du destin à sa volont'
TextItem          text            body       #/body          "QUAND : À n'importe quelle phase, juste après que vous avez fait un de"
ListItem          list_item       body       #/groups/120    "Jet d'avance"
ListItem          list_item       body       #/groups/120    '▪Jet de charge'
ListItem          list_item       body       #/groups/120    '▪Jet de dégâts'
ListItem          list_item       body       #/groups/120    '▪Jet de risque'
ListItem          list_item       body       #/groups/120    '▪Jet de touche'
ListItem          list_item       body       #/groups/120    '▪Jet de sauvegarde'
ListItem          list_item       body       #/groups/120    '▪Jet de blessure'
ListItem          list_item       body       #/groups/120    "Un jet pour déterminer le nombre d'attaques générées par une arme."
TextItem          text            body       #/body          'CIBLE : Cette unité ou figurine.'
TextItem          text            body       #/body          "EFFET : Vous relancez ce jet. Si vous jetez plus d'un dé en même temps"
SectionHeaderItem section_header  body       #/body          'DÉFI ÉPIQUE 15.03'
SectionHeaderItem section_header  body       #/body          'STRATAGÈME DE BASE'
TextItem          text            body       #/body          "Les légendes du 41 e Millénaire abondent de duels mortels entre d'illu"
TextItem          text            body       #/body          "QUAND : À la phase de Combat, juste après qu'une unité de PERSONNAGE a"
TextItem          text            body       #/body          'CIBLE : Cette unité de PERSONNAGE.'
TextItem          text            body       #/body          "EFFET : Choisissez 1 figurine de PERSONNAGE de votre unité. Jusqu'à la"
SectionHeaderItem section_header  body       #/body          'COURAGE INSENSÉ 15.04'
SectionHeaderItem section_header  body       #/body          'STRATAGÈME DE BASE'
TextItem          text            body       #/body          'Indifférents à leur propre survie, ces guerriers tiennent leurs positi'
TextItem          text            body       #/body          "QUAND : À l'étape d'Ébranlement de votre phase de Commandement, juste "
TextItem          text            body       #/body          'CIBLE : Cette unité.'
TextItem          text            body       #/body          "EFFET : Ce jet d'ébranlement est"
TextItem          text            body       #/body          'automatiquement réussi.'
TextItem          text            body       #/body          "RESTRICTIONS : Vous ne pouvez pas utiliser ce stratagème plus d'une fo"
PictureItem       picture         body       #/body          ''
TextItem          text            body       #/body          '1PC'
PictureItem       picture         body       #/body          ''
TextItem          text            body       #/body          '1PC'
PictureItem       picture         body       #/body          ''
SectionHeaderItem section_header  body       #/body          'EXPLOSIFS 15.05'
SectionHeaderItem section_header  body       #/body          'STRATAGÈME DE BASE'
TextItem          text            body       #/body          'Armant leurs grenades et autres explosifs, ces guerriers reculent et e'
TextItem          text            body       #/body          'QUAND : À votre phase de Tir.'
TextItem          text            body       #/body          'CIBLE : 1 unité à EXPLOSIFS/GRENADES non engagée amie qui est éligible'
TextItem          text            body       #/body          'EFFET : Résolvez la séquence suivante :'
ListItem          list_item       body       #/groups/121    'Choisissez 1 figurine à EXPLOSIFS/GRENADES de votre unité.'
ListItem          list_item       body       #/groups/121    'Choisissez 1 unité ennemie non engagée à 8" ou moins et visible de cet'
ListItem          list_item       body       #/groups/121    'Jetez six D6 : pour chaque 4+, cette unité'
ListItem          list_item       body       #/groups/121    'ennemie subit 1 blessure mortelle (06.02).'
SectionHeaderItem section_header  body       #/body          'IMPACT ÉCRASANT 15.06'
SectionHeaderItem section_header  body       #/body          'STRATAGÈME DE BASE'
TextItem          text            body       #/body          'En cas extrême, les blindés et les monstres peuvent utiliser leur carr'
TextItem          text            body       #/body          "QUAND : À votre phase de Charge, juste après qu'une unité de MONSTRE/V"
TextItem          text            body       #/body          'CIBLE : Cette unité de MONSTRE/VÉHICULE.'
TextItem          text            body       #/body          'EFFET : Résolvez la séquence suivante :'
ListItem          list_item       body       #/groups/122    'Choisissez 1 unité ennemie engagée avec votre unité.'
ListItem          list_item       body       #/groups/122    'Choisissez 1 figurine de votre unité engagée avec cette unité ennemie.'
ListItem          list_item       body       #/groups/122    "Jetez autant de D6 que la caractéristique d'E de cette figurine : pour"
ListItem          list_item       body       #/groups/122    "1 blessure mortelle ; pour chaque 5+, l'unité ennemie subit 1 blessure"
ListItem          list_item       body       #/groups/122    'maximum de 6 blessures mortelles par unité).'
TextItem          text            body       #/body          '1PC'
PictureItem       picture         body       #/body          ''
TextItem          text            body       #/body          '1PC'
PictureItem       picture         body       #/body          ''
PictureItem       picture         body       #/body          ''
TextItem          page_footer     furniture  #/body          '56'

## 3.2 nettoyage simple

éléments très court

In [ ]:
courts = df_items.loc[df_items["texte"].str.len() < 25, "texte"]
print(courts.value_counts().head(40))

normalisation du texte

In [158]:
REMPLACEMENTS = str.maketrans({
    # Ligatures typographiques
    "ﬀ": "ff", "ﬁ": "fi", "ﬂ": "fl", "ﬃ": "ffi", "ﬄ": "ffl",
    # Apostrophes
    "’": "'", "‘": "'", "ʼ": "'",
    # Guillemets anglais et double prime (pouces) -> guillemet droit
    "“": '"', "”": '"', "„": '"', "″": '"',
})
MOTIF_PUCE = re.compile(r"^[▪▫•●]\s*")

def normaliser_texte(texte: str, est_tableau: bool = False) -> str:
    """Normalise le texte d'un élément sans NFKC, pour préserver ½, pouces, etc.

    Args:
        texte: texte brut de l'élément.
        est_tableau: True pour un tableau Markdown (on préserve les retours à la ligne).

    Returns:
        Texte normalisé.
    """
    t = "".join(c for c in texte if c.isspace() or unicodedata.category(c) not in ("Cc", "Cf"))
    t = t.translate(REMPLACEMENTS)
    if est_tableau:
        t = re.sub(r"[^\S\n]+", " ", t)  # blancs sauf retours à la ligne
        return "\n".join(ligne.strip() for ligne in t.split("\n")).strip()
    t = re.sub(r"\s+", " ", t).strip()
    return MOTIF_PUCE.sub("- ", t)

annotation

In [159]:
MOTIF_CODE_CITE = re.compile(r"\b\d{2}\.\d{2}\b")
ZONES_HORS_REGLES = {"Index des règles de base", "(ouverture de chapitre)", "introduction"}
DEBUT_REGLE_STRATAGEME = ("QUAND", "CIBLE", "EFFET", "RESTRICTIONS")
PONCTUATION_FINALE = (".", ":", ";", "!", "?")

def ressemble_a_une_etiquette(t: str) -> bool:
    """Étiquette de schéma : tout en majuscules / sans lettres, ou ≤ 3 mots sans ponctuation finale.

    Args:
        t: texte normalisé.

    Returns:
        True si le texte a la forme d'une étiquette plutôt que d'un fragment de phrase.
    """
    return t.upper() == t or (len(t.split()) <= 3 and not t.endswith(PONCTUATION_FINALE))


def motif_ligne(ligne: pd.Series) -> str | None:
    """Motif d'exclusion d'un élément (première règle qui s'applique), ou None.

    Args:
        ligne: une ligne de df_items, texte déjà normalisé.

    Returns:
        Nom du motif, ou None si l'élément est conservé.
    """
    t = ligne["texte"]
    if ligne["chapitre"] == "LIMINAIRE" or ligne["section_titre"] in ZONES_HORS_REGLES:
        return "zone_hors_regles"
    if not any(c.isalnum() for c in t):  # ½ compte comme alphanumérique : '½"' n'est pas vide
        return "sans_contenu"
    if re.fullmatch(r"\d{2}", t) and t == ligne["section_num"]:
        return "numero_section"
    if t.isdigit() and ligne["page"] == int(t):
        return "numero_page"
    if re.fullmatch(r"\d+\s*PC", t):
        return "cout_isole"

    zone_voir_aussi = str(ligne["sous_partie"]).startswith("VOIR AUSSI")
    renvoi_code = t.startswith("- ") and re.search(r"\d{2}\.\d{2}$", t)
    if renvoi_code or (zone_voir_aussi and len(t) <= 50):
        return "renvoi"
    if (ligne["dans_image"] and ligne["type_contenu"] != "table"
            and len(t) < 25 and ":" not in t and ressemble_a_une_etiquette(t)):
        return "etiquette_image"

    return None

def annoter_nettoyage(df: pd.DataFrame) -> pd.DataFrame:
    """Normalise le texte et annote chaque élément avec un éventuel motif d'exclusion.

    Rien n'est supprimé : les colonnes ajoutées permettent d'auditer puis de filtrer.

    Args:
        df: df_items issu de la cellule 8.

    Returns:
        Copie de df avec texte_brut, texte (normalisé), codes_cites, motif_exclusion, a_relire.
    """
    df = df.copy()
    if "texte_brut" not in df:  # la cellule peut être relancée sans écraser le texte d'origine
        df["texte_brut"] = df["texte"]
    df["texte"] = [normaliser_texte(t, est_tableau=(tc == "table"))
                   for t, tc in zip(df["texte_brut"], df["type_contenu"])]
    df["codes_cites"] = df["texte"].map(MOTIF_CODE_CITE.findall)

    # Règles élément par élément
    df["motif_exclusion"] = df.apply(motif_ligne, axis=1)

    # Lore des stratagèmes : texte avant la première ligne QUAND/CIBLE/… de chaque stratagème
    dans_strat = df["sous_partie"].eq("STRATAGÈME DE BASE") & df["motif_exclusion"].isna()
    debut_regle = df["texte"].str.startswith(DEBUT_REGLE_STRATAGEME) & dans_strat
    regle_commencee = debut_regle.groupby(df["code"].fillna("_")).cummax()
    lore = dans_strat & ~regle_commencee & df["type_contenu"].eq("text")
    df.loc[lore, "motif_exclusion"] = "lore_stratageme"

        # Doublons : même code et même texte, mais sur une autre page que la 1re occurrence.
    # Les répétitions sur une même page (logigrammes, Q/R, tableaux) sont légitimes.
    cle = ["code", "texte"]
    premiere_page = df.groupby(cle, dropna=False)["page"].transform("min")
    doublon = (df.duplicated(subset=cle, keep="first")
               & df["page"].ne(premiere_page)
               & df["motif_exclusion"].isna())
    df.loc[doublon, "motif_exclusion"] = "doublon"

    df["a_relire"] = df["motif_exclusion"].isna() & (df["texte"].str.len() < 15)
    return df

In [160]:
df_items = annoter_nettoyage(df_items)

In [161]:
df_items

,ordre,chapitre,section_num,section_titre,code,sous_section,sous_partie,page,type_contenu,dans_image,texte,texte_brut,codes_cites,motif_exclusion,a_relire
0,0,LIMINAIRE,NaN,NaN,NaN,NaN,NaN,1,text,False,"Dans les ténèbres d'un lointain futur, l'Human...","Dans les ténèbres d'un lointain futur, l'Human...",[],zone_hors_regles,False
1,1,LIMINAIRE,NaN,NaN,NaN,NaN,NaN,1,text,False,Il n'y a pas de paix. Pas de répit. Pas de par...,Il n'y a pas de paix. Pas de répit. Pas de par...,[],zone_hors_regles,False
2,2,LIMINAIRE,NaN,NaN,NaN,NaN,NaN,2,table,False,| Chaque section et sous-section possède ici u...,| Chaque section et sous-section possède ici u...,[],zone_hors_regles,False
3,4,INTRODUCTION,00,introduction,NaN,NaN,NaN,4,text,False,Bienvenue dans les Règles de Base de Warhammer...,Bienvenue dans les Règles de Base de Warhammer...,[],zone_hors_regles,False
4,5,INTRODUCTION,00,introduction,NaN,NaN,NaN,4,text,False,"Warhammer 40,000 est un jeu de bataille sur ta...","Warhammer 40,000 est un jeu de bataille sur ta...",[],zone_hors_regles,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1316,1781,RÉFÉRENCES,NaN,Appendices des règles,NaN,NaN,FAQ,88,text,False,R : Non.,R : Non.,[],NaN,True
1317,1782,RÉFÉRENCES,NaN,Appendices des règles,NaN,NaN,FAQ,88,text,False,Q : Une unité qui est éligible pour effectuer ...,Q : Une unité qui est éligible pour effectuer ...,[],NaN,False
1318,1783,RÉFÉRENCES,NaN,Appendices des règles,NaN,NaN,FAQ,88,text,False,"R : Non. Parfois, une unité peut devenir engag...","R : Non. Parfois, une unité peut devenir engag...",[],NaN,False
1319,1784,RÉFÉRENCES,NaN,Appendices des règles,NaN,NaN,FAQ,88,text,False,Q : Une unité peut-elle embarquer dans un TRAN...,Q : Une unité peut-elle embarquer dans un TRAN...,[],NaN,False
1320,1785,RÉFÉRENCES,NaN,Appendices des règles,NaN,NaN,FAQ,88,text,False,R : Non. Les mouvements d'éclaireur se produis...,R : Non. Les mouvements d'éclaireur se produis...,[],NaN,False

audit

In [162]:
# 1. Volume par motif
display(df_items["motif_exclusion"].value_counts(dropna=False).rename("nb_elements"))

# 2. Échantillon par motif : vérifier qu'aucune règle n'est emportée
for motif, g in df_items.dropna(subset=["motif_exclusion"]).groupby("motif_exclusion"):
    print(f"\n=== {motif} ({len(g)}) ===")
    for t in g["texte"].sample(min(8, len(g)), random_state=0):
        print("  ·", t[:90])

# 3. Signalés à relire (courts, sans motif)
print("\n=== à relire ===")
print(df_items.loc[df_items["a_relire"], "texte"].value_counts().head(30))

# 4. Contrôle des caractères sensibles : seul '"' doit augmenter (guillemets unifiés)
SENSIBLES = ["½", '"', "+", "×", "«", "»", "…", "-", "/"]
controle = pd.DataFrame(
    {c: [df_items["texte_brut"].str.count(re.escape(c)).sum(),
         df_items["texte"].str.count(re.escape(c)).sum()] for c in SENSIBLES},
    index=["brut", "normalisé"],
)
display(controle)

# 5. Mots coupés en fin de ligne restants (à inspecter, pas corrigés automatiquement)
coupes = df_items["texte"].str.contains(r"[a-zà-ÿ]- [a-zà-ÿ]")
print(f"\n{coupes.sum()} élément(s) avec une coupure suspecte")
print(df_items.loc[coupes, "texte"].head(5).tolist())

motif_exclusion
NaN                 997
etiquette_image     199
renvoi               47
numero_section       30
zone_hors_regles     18
lore_stratageme      10
doublon               9
cout_isole            9
sans_contenu          2
Name: nb_elements, dtype: int64

=== cout_isole (9) ===
  · 2PC
  · 1PC
  · 1PC
  · 1PC
  · 1PC
  · 1PC
  · 1PC
  · 1PC

=== doublon (9) ===
  · Quand vous choisissez des cibles de charge, vous pouvez choisir une ou plusieurs unités en
  · Ensuite, chaque joueur consulte sa mission ; si l'un ou les deux joueurs ont rempli un ou
  · Résolvez d'abord les règles déclenchées à ce stade autres que les règles de mission.
  · Bondir pour Défendre : Quand vous choisissez des cibles de charge, vous pouvez seulement c
  · Scannez le code ci-dessous pour installer dès maintenant l'appli Warhammer 40,000.
  · Quand vous faites le jet de charge, si le résultat est supérieur à 6 (après modificateurs)
  · EFFET : Résolvez une charge avec votre unité (11.02). Ce faisant, avant de faire le jet de
  · L'unité ROUGE attaque. On choisit les armes suivantes avec lesquelles effectuer des attaqu

=== etiquette_image (199) ===
  · APTITUDES
  · A
  · 2.
  · 2"
  · 15"
  · PLEIN
  · ►Tirs au Dé
  · DÉBUT DE LA PHASE DE TIR

=== lore_stratageme (10) ===
  · Indifférents à leur propre survie, ces guerriers tiennent leurs positions envers et contre
  · Des cris de guerre montent et vos guerriers se ruent tête baissée face à l'offensive adver
  · En cas extrême, les blindés et les monstres peuvent utiliser leur carrure comme arme, éper
  · En combat rapproché, la moindre hésitation peut laisser entrevoir une faille à exploiter.
  · Les légendes du 41 e Millénaire abondent de duels mortels entre d'illustres champions.
  · Une grêle de tirs peut repousser l'ennemi qui approche.
  · Le plus habile aura du mal à toucher une cible voilée par un nuage de fumée.
  · Armant leurs grenades et autres explosifs, ces guerriers reculent et envoient la mort au b

=== numero_section (30) ===
  · 03
  · 24
  · 11
  · 08
  · 24
  · 21
  · 24
  · 09

=== renvoi (47) ===
  · ►Modifier les Dégâts
  · - Aérodynes 23.00
  · ►Caractéristiques Aléatoires
  · - Aptitudes Psychiques 22.03
  · - Mouvement d'Arrivée 20.04
  · - Terrain 13.00
  · - Jets de Risque 06.03
  · - Jets d'Ébranlement 01.07

=== sans_contenu (2) ===
  · -›
  · -›

=== zone_hors_regles (18) ===
  · Il n'y a pas de paix. Pas de répit. Pas de pardon. Il n'y a que la guerre.
  · Chaque partie de Warhammer 40,000 s'inscrit dans le cadre d'une mission, que vous devrez g
  · Quelle que soit la faction que vous souhaitez collectionner et avec laquelle livrer des ba
  · Les pages suivantes contiennent les Règles de Base que tout joueur de Warhammer 40,000 doi
  · Scannez le code ci-dessous pour installer dès maintenant l'appli Warhammer 40,000.
  · Warhammer 40,000 est un jeu de bataille sur table dans lequel chaque joueur dirige une arm
  · | Chaque section et sous-section possède ici un numéro de référence interne. Le tableau ci
  · 6

=== à relire ===
texte
-› non modifié    2
EN TIRANT :       2
R : Non.          2
- 1 Boss Nob      1
►Détruit          1
en cohésion.      1
Non engagée.      1
JETS DE TOUCHE    1
-1 au Jet de      1
ÉBRANLEMENT       1
Actions 16.00     1
CHARGER           1
S'INSÉRER         1
COMBATTRE         1
CONSOLIDER        1
DE COMBATTRE ?    1
- Dense :         1
e                 1
taille.           1
+1PC              1
ses attaques.     1
57                1
Jet d'avance      1
Ressuscité        1
Name: count, dtype: int64

           ½    "   +  ×  «  »  …     -   /
brut       5  129  59  0  0  0  0  1492  64
normalisé  5  129  59  0  0  0  0  1600  64

4 élément(s) avec une coupure suspecte
["Cette unité a un effectif initial de 5. Il lui reste deux figurines, elle est donc en dessous de son demi- effectif et on doit faire un jet d'ébranlement pour elle.", "Ce VÉHICULE a un effectif initial de 1 et une caracté- ristique de PV de 11. Il lui reste 3 points de vie, il est donc en dessous de son demi-effectif et on doit faire un jet d'ébranlement pour lui.", "Cette figurine d'INFANTERIE ne se déplace pas par- dessus ni à travers des éléments de terrain. Son mouvement à travers la zone de terrain indiquée se fait donc sans encombre.", "Il y a une zone de terrain occultante entre toutes les figuri- nes des unités A et D, donc l'une n'est pas visible de l'autre."]

In [163]:
for motif in ["renvoi", "etiquette_image"]:
    g = df_items[df_items["motif_exclusion"] == motif]
    print(f"\n=== {motif} : les 10 plus longs ===")
    for t in g.loc[g["texte"].str.len().nlargest(10).index, "texte"]:
        print("  ·", t[:100])

=== renvoi : les 10 plus longs ===
  · - Se Déplacer à la Verticale 13.06
  · - Mouvement de Consolidation 12.08
  · - Mouvement de Débarquement 18.04
  · - Aptitudes d'Équipement 22.04
  · APTITUDES DES UNITÉS ATTACHÉES
  · - Phase de Commandement 08.00
  · - Réserves Stratégiques 20.00
  · - Mouvement de Retraite 09.07
  · - Mouvement d'Insertion 12.03
  · - Mouvement d'Éclaireur 24.32

=== etiquette_image : les 10 plus longs ===
  · DÉBUT DE LA PHASE DE TIR
  · FIN DE LA PHASE DE TIR
  · ►Séquençage de Règles
  · ►Réussite Automatique
  · OPTIONS D'ÉQUIPEMENT
  · COMPOSITION D'UNITÉ
  · Objectif de Terrain
  · Objectif de Terrain
  · Objectif de Terrain
  · Objectif de Terrain

## 3.3 Choix pour le découpage en chunks

Cible / max	 --> Effet attendu

250 / 400	--> Plus précis, mais davantage de règles coupées en morceaux

400 / 600 (spec) -->	Compromis standard ; la plupart des sous-sections devraient tenir entières

600 / 800	--> Presque rien n'est coupé, au prix de vecteurs plus « dilués » pour les grosses sous-sections

In [164]:
tokenizer = AutoTokenizer.from_pretrained("BAAI/bge-m3")  # tokenizer seul, pas le modèle

Reconstruction du texte des unités

In [152]:

def nb_tokens(texte: str) -> int:
    """Nombre de tokens BGE-M3 d'un texte (sans tokens spéciaux)."""
    return len(tokenizer(texte, add_special_tokens=False)["input_ids"])

def valeur(x):
    """Convertit les NaN pandas en None."""
    return None if pd.isna(x) else x

def construire_prefixe(chapitre, section_num, section_titre, code, sous_section) -> str:
    """Construit le chemin de contexte « Chapitre > NN Section > NN.NN Sous-section ».

    Returns:
        Préfixe sans les niveaux absents.
    """
    niveaux = [
        chapitre,
        " ".join(p for p in (section_num, section_titre) if p),
        " ".join(p for p in (code, sous_section) if p),
    ]
    return " > ".join(n for n in niveaux if n)

def rendre_unite(g: pd.DataFrame, prefixe: str) -> str:
    """Reconstruit le texte Markdown d'un groupe d'éléments, titres de sous-parties réinsérés.

    Args:
        g: éléments du groupe, triés dans l'ordre de lecture.
        prefixe: chemin de contexte placé en tête.

    Returns:
        Texte tel qu'il sera embarqué.
    """
    lignes, sous_partie_courante = [prefixe, ""], None
    for sp, tc, texte in zip(g["sous_partie"], g["type_contenu"], g["texte"]):
        sp = valeur(sp)
        if sp and sp != sous_partie_courante:
            lignes += ["", f"### {sp}"]
            sous_partie_courante = sp
        lignes += ["", texte, ""] if tc == "table" else [texte]
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lignes)).strip()

mesure par sous-section et par sous-partie

In [145]:
df_contenu = df_items[df_items["motif_exclusion"].isna()].sort_values("ordre")
df_contenu_motif = df_items[df_items["motif_exclusion"].notna()].sort_values("ordre")

In [150]:
np.unique(df_contenu_motif["motif_exclusion"])

array(['cout_isole', 'doublon', 'etiquette_image', 'lore_stratageme',
       'numero_page', 'numero_section', 'renvoi', 'sans_contenu',
       'zone_hors_regles'], dtype=object)

In [153]:
CLES_UNITE = ["chapitre", "section_num", "section_titre", "code", "sous_section"]

unites = []
for cles, g in df_contenu.groupby(CLES_UNITE, dropna=False, sort=False):
    cles = [valeur(c) for c in cles]
    prefixe = construire_prefixe(*cles)
    tailles_sp = [nb_tokens(rendre_unite(sg, prefixe))
                  for _, sg in g.groupby(g["sous_partie"].fillna("∅"), sort=False)]
    unites.append({
        **dict(zip(CLES_UNITE, cles)),
        "nb_elements": len(g),
        "page_min": g["page"].min(), "page_max": g["page"].max(),
        "nb_tokens": nb_tokens(rendre_unite(g, prefixe)),
        "nb_sous_parties": len(tailles_sp),
        "max_tokens_sous_partie": max(tailles_sp),
        "contient_table": (g["type_contenu"] == "table").any(),
    })
df_unites = pd.DataFrame(unites)
print(f"{len(df_unites)} unités (sous-sections + introductions de section)")

181 unités (sous-sections + introductions de section)

In [154]:
df_unites

,chapitre,section_num,section_titre,code,sous_section,nb_elements,page_min,page_max,nb_tokens,nb_sous_parties,max_tokens_sous_partie,contient_table
0,INTRODUCTION,00,introduction,NaN,NaN,12,4,5,929,3,737,False
1,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,NaN,NaN,1,8,8,77,1,77,False
2,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,01.01,ARMÉES,1,8,8,91,1,91,False
3,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,01.02,UNITÉS ET FIGURINES,5,8,8,223,1,223,False
4,RÈGLES ÉLÉMENTAIRES,01,Concepts de base,01.03,JOUEUR ACTIF ET JOUEUR ADVERSE,5,8,8,267,1,267,False
...,...,...,...,...,...,...,...,...,...,...,...,...
176,RÉFÉRENCES,24,Aptitudes de base,24.26,[TIR UNIQUE],4,85,85,181,1,181,False
177,RÉFÉRENCES,24,Aptitudes de base,24.37,[TORRENT],2,85,85,77,1,77,False
178,RÉFÉRENCES,24,Aptitudes de base,24.23,[TOUCHES FATALES],3,85,85,190,1,190,False
179,RÉFÉRENCES,24,Aptitudes de base,24.36,[TOUCHES SOUTENUES],3,85,85,187,1,187,False
180,RÉFÉRENCES,NaN,Appendices des règles,NaN,NaN,33,86,88,2454,12,411,True

rapport d'audit

In [155]:
# 1. Distribution des tailles
print(df_unites["nb_tokens"].describe(percentiles=[.5, .75, .9, .95]).round(0))

# 2. Combien d'unités dépassent chaque seuil candidat
for seuil in (250, 400, 600, 800):
    trop = df_unites["nb_tokens"] > seuil
    print(f"> {seuil:>3} tokens : {trop.sum():>3} unités ({trop.mean():.0%})")

# 3. Pour chaque budget max : le découpage par sous-parties suffit-il ?
for seuil in (400, 600, 800):
    gros = df_unites[df_unites["nb_tokens"] > seuil]
    print(f"Budget {seuil} : {len(gros)} unités à découper, dont "
          f"{(gros['max_tokens_sous_partie'] > seuil).sum()} avec une sous-partie seule encore trop grosse")

# 4. Les 15 plus grosses unités
display(df_unites.nlargest(15, "nb_tokens")[
    ["code", "sous_section", "section_titre", "nb_tokens", "nb_sous_parties",
     "max_tokens_sous_partie", "contient_table", "page_min", "page_max"]])

# 5. Les très petites unités, et la taille des tableaux
print("\nUnités < 50 tokens :", (df_unites["nb_tokens"] < 50).sum())
tables = df_contenu.loc[df_contenu["type_contenu"] == "table", "texte"].map(nb_tokens)
print("Tableaux (tokens) :", tables.describe().round(0).to_dict())

count     181.0
mean      242.0
std       286.0
min        36.0
50%       157.0
75%       292.0
90%       492.0
95%       643.0
max      2454.0
Name: nb_tokens, dtype: float64
> 250 tokens :  56 unités (31%)
> 400 tokens :  28 unités (15%)
> 600 tokens :  12 unités (7%)
> 800 tokens :   4 unités (2%)
Budget 400 : 28 unités à découper, dont 10 avec une sous-partie seule encore trop grosse
Budget 600 : 12 unités à découper, dont 1 avec une sous-partie seule encore trop grosse
Budget 800 : 4 unités à découper, dont 0 avec une sous-partie seule encore trop grosse

,code,sous_section,section_titre,nb_tokens,nb_sous_parties,max_tokens_sous_partie,contient_table,page_min,page_max
180,NaN,NaN,Appendices des règles,2454,12,411,True,86,88
30,05.04,INFLIGER DES DÉGÂTS,Séquence d'attaque,2164,12,451,True,19,23
18,03.01,DÉPLACER DES UNITÉS,Mouvement,1085,10,226,False,12,14
0,NaN,NaN,introduction,929,3,737,False,4,5
82,13.06,TERRAIN ET MOUVEMENT,Terrain,800,4,304,False,48,49
25,04.03,RÉSOUDRE LES ATTAQUES,Effectuer des attaques,786,6,494,False,17,17
69,12.03,MOUVEMENT D'INSERTION,Phase de combat,746,6,301,False,38,40
87,13.11,PLEIN,Terrain,661,3,339,False,50,51
81,13.05,DENSE,Terrain,659,4,269,False,46,48
120,19.04,APTITUDES DES UNITÉS ATTACHÉES,Unités attachées,643,3,365,True,67,67
93,15.11,INTERVENTION HÉROÏQUE,Stratagèmes,628,2,549,False,55,57
109,17.03,TIRER SUR DES MONSTRES ET DES VÉHICULES ENGAGÉS,Monstres et véhicules,607,2,387,False,62,63
105,16.01,EFFECTUER DES ACTIONS,Actions,568,4,225,False,58,58
52,09.07,MOUVEMENT DE RETRAITE,Phase de mouvement,541,3,290,False,33,33
74,12.08,MOUVEMENT DE CONSOLIDATION,Phase de combat,532,1,532,False,42,42

Unités < 50 tokens : 11
Tableaux (tokens) : {'count': 5.0, 'mean': 194.0, 'std': 56.0, 'min': 110.0, '25%': 181.0, '50%': 190.0, '75%': 242.0, 'max': 247.0}

Chunk	Contenu	Tokens	Pourquoi
1	A + B	300	ajouter C dépasserait 400, on ferme
2	C	451	trop grosse pour être regroupée, mais sous 600
3	D + E	340	on regroupe ce qui reste


Chaque chunk commence par le même préfixe (… > 05.04 INFLIGER DES DÉGÂTS), suivi des titres de ses sous-parties.

## 3.4 Découpage en chunk

paramètres

In [165]:
import uuid

CIBLE_TOKENS = 400   # taille visée quand on regroupe des sous-parties
MAX_TOKENS = 600     # au-delà, une sous-section est découpée
EDITION = "11e"
SOURCE = "livre_regles_principal"
ESPACE_UUID = uuid.uuid5(uuid.NAMESPACE_URL, "assistant-regles-w40k")

def taille(elements: pd.DataFrame, prefixe: str) -> int:
    """Taille en tokens du texte rendu d'un groupe d'éléments, préfixe compris."""
    return nb_tokens(rendre_unite(elements, prefixe))

les trois fonctions de découpage

In [166]:
def blocs_sous_parties(g: pd.DataFrame) -> list[pd.DataFrame]:
    """Découpe une unité en blocs de sous-parties contiguës, dans l'ordre de lecture.

    Args:
        g: éléments d'une unité, triés par ordre.

    Returns:
        Liste de blocs ; les éléments sans sous-partie forment leur propre bloc.
    """
    cle = g["sous_partie"].fillna("∅")
    numero_bloc = (cle != cle.shift()).cumsum()
    return [bloc for _, bloc in g.groupby(numero_bloc, sort=False)]


def decouper_paragraphes(bloc: pd.DataFrame, prefixe: str) -> list[pd.DataFrame]:
    """Filet de sécurité : découpe un bloc trop gros aux frontières d'éléments, avec chevauchement.

    Le dernier élément d'un morceau est répété en tête du suivant (paragraphe entier,
    jamais une coupe en milieu de phrase). Un élément seul hors budget reste entier.

    Args:
        bloc: éléments d'une sous-partie dépassant MAX_TOKENS.
        prefixe: chemin de contexte.

    Returns:
        Liste de morceaux.
    """
    morceaux, courant = [], []
    for i in range(len(bloc)):
        element = bloc.iloc[[i]]
        if taille(element, prefixe) > MAX_TOKENS:  # ex. très gros tableau : gardé entier
            if courant:
                morceaux.append(pd.concat(courant))
            morceaux.append(element)
            courant = []
            continue
        if courant and taille(pd.concat(courant + [element]), prefixe) > CIBLE_TOKENS:
            morceaux.append(pd.concat(courant))
            # Chevauchement seulement si le morceau fermé contient plusieurs éléments
            # (sinon il serait entièrement inclus dans le suivant).
            chevauchement = courant[-1]
            avec_chevauchement = len(courant) > 1 and \
                taille(pd.concat([chevauchement, element]), prefixe) <= MAX_TOKENS
            courant = [chevauchement, element] if avec_chevauchement else [element]
        else:
            courant.append(element)
    if courant:
        morceaux.append(pd.concat(courant))
    return morceaux


def decouper_unite(g: pd.DataFrame, prefixe: str) -> list[pd.DataFrame]:
    """Découpe une sous-section en morceaux respectant le budget.

    Niveau 1 : l'unité tient dans MAX_TOKENS -> un seul morceau.
    Niveau 2 : sinon, regroupement de sous-parties contiguës jusqu'à CIBLE_TOKENS.
    Niveau 3 : une sous-partie seule > MAX_TOKENS -> découpage par paragraphes.

    Args:
        g: éléments de l'unité, triés par ordre.
        prefixe: chemin de contexte.

    Returns:
        Liste de morceaux (DataFrames d'éléments).
    """
    if taille(g, prefixe) <= MAX_TOKENS:
        return [g]

    morceaux, courant = [], []
    for bloc in blocs_sous_parties(g):
        if taille(bloc, prefixe) > MAX_TOKENS:
            if courant:
                morceaux.append(pd.concat(courant))
                courant = []
            morceaux.extend(decouper_paragraphes(bloc, prefixe))
            continue
        if courant and taille(pd.concat(courant + [bloc]), prefixe) > CIBLE_TOKENS:
            morceaux.append(pd.concat(courant))
            courant = [bloc]
        else:
            courant.append(bloc)
    if courant:
        morceaux.append(pd.concat(courant))
    return morceaux

construction des chunks et de leurs métadonnées, puis sauvegarde en JSONL

In [167]:
def construire_chunk(morceau: pd.DataFrame, cles: tuple, prefixe: str,
                     partie: int, nb_parties: int) -> dict:
    """Assemble le texte et les métadonnées d'un chunk.

    Args:
        morceau: éléments du chunk.
        cles: (chapitre, section_num, section_titre, code, sous_section).
        prefixe: chemin de contexte.
        partie: rang du chunk dans son unité (à partir de 1).
        nb_parties: nombre de chunks de l'unité.

    Returns:
        dict prêt à être sérialisé en JSONL.
    """
    chapitre, section_num, section_titre, code, sous_section = cles
    texte = rendre_unite(morceau, prefixe)
    n = nb_tokens(texte)
    ordres = morceau["ordre"].tolist()
    codes_cites = sorted({c for liste in morceau["codes_cites"] for c in liste} - {code})
    return {
        "id": str(uuid.uuid5(ESPACE_UUID, f"{SOURCE}|{ordres[0]}|{ordres[-1]}")),
        "texte": texte,
        "chapitre": chapitre,
        "section_num": section_num,
        "section_titre": section_titre,
        "code": code,
        "sous_section": sous_section,
        "sous_parties": list(dict.fromkeys(v for v in morceau["sous_partie"] if pd.notna(v))),
        "page_debut": int(morceau["page"].min()),
        "page_fin": int(morceau["page"].max()),
        "type_contenu": "table" if (morceau["type_contenu"] == "table").all() else "regle",
        "edition": EDITION,
        "source": SOURCE,
        "codes_cites": codes_cites,
        "partie": partie,
        "nb_parties": nb_parties,
        "nb_tokens": n,
        "hors_budget": n > MAX_TOKENS,
        "ordres": ordres,
    }

In [170]:
CLES_UNITE

['chapitre', 'section_num', 'section_titre', 'code', 'sous_section']

In [168]:
df_contenu = df_items[df_items["motif_exclusion"].isna()].sort_values("ordre")

chunks = []
for cles, g in df_contenu.groupby(CLES_UNITE, dropna=False, sort=False):
    cles = tuple(valeur(c) for c in cles)
    prefixe = construire_prefixe(*cles)
    morceaux = decouper_unite(g, prefixe)
    chunks += [construire_chunk(m, cles, prefixe, i, len(morceaux))
               for i, m in enumerate(morceaux, start=1)]

df_chunks = pd.DataFrame(chunks)

FICHIER_CHUNKS = DOSSIER_SORTIE / "chunks.jsonl"
df_chunks.to_json(FICHIER_CHUNKS, orient="records", lines=True, force_ascii=False)
print(f"✓ {len(df_chunks)} chunks écrits dans {FICHIER_CHUNKS.relative_to(RACINE)}")

✓ 207 chunks écrits dans data/interim/chunks.jsonl

validation

In [169]:
# 1. Tailles
print(df_chunks["nb_tokens"].describe(percentiles=[.5, .9, .95]).round(0))
print("Chunks hors budget :", df_chunks["hors_budget"].sum())

# 2. Unités découpées et nombre de parties
decoupees = df_chunks[df_chunks["nb_parties"] > 1]
display(decoupees.groupby(["section_titre", "code"], dropna=False, sort=False)
        .agg(nb_parties=("partie", "size"), tokens=("nb_tokens", list)))

# 3. Couverture : chaque élément conservé doit apparaître dans au moins un chunk
tous_ordres = pd.Series([o for liste in df_chunks["ordres"] for o in liste])
manquants = set(df_contenu["ordre"]) - set(tous_ordres)
print(f"\nÉléments non couverts : {len(manquants)}")
print(f"Éléments répétés (chevauchement) : {(tous_ordres.value_counts() > 1).sum()}")

# 4. Relecture : unités découpées emblématiques + échantillon aléatoire
def afficher_chunk(c) -> None:
    """Affiche un chunk avec ses principales métadonnées."""
    print("=" * 80)
    print(f"[{c.code or '—'}] partie {c.partie}/{c.nb_parties} · p. {c.page_debut}-{c.page_fin} · "
          f"{c.nb_tokens} tokens · {c.type_contenu} · renvois {c.codes_cites}")
    print("-" * 80)
    print(c.texte)

echantillon = pd.concat([
    df_chunks[df_chunks["code"] == "05.04"].head(3),
    df_chunks[df_chunks["code"] == "15.11"],
    df_chunks.sample(10, random_state=0),
])
for c in echantillon.itertuples():
    afficher_chunk(c)

count    207.0
mean     210.0
std      132.0
min       36.0
50%      181.0
90%      391.0
95%      454.0
max      568.0
Name: nb_tokens, dtype: float64
Chunks hors budget : 0

                              nb_parties  \
section_titre          code
Mouvement              03.01           4
Effectuer des attaques 04.03           2
Séquence d'attaque     05.04           7
Phase de combat        12.03           3
Terrain                13.05           2
                       13.06           3
                       13.11           2
Stratagèmes            15.11           2
Monstres et véhicules  17.03           2
Unités attachées       19.04           3
Appendices des règles  NaN             8

                                                                tokens
section_titre          code
Mouvement              03.01                      [335, 383, 320, 122]
Effectuer des attaques 04.03                                [494, 321]
Séquence d'attaque     05.04       [451, 288, 360, 326, 287, 358, 274]
Phase de combat        12.03                           [361, 320, 111]
Terrain                13.05                                [345, 335]
                       13.06                           [304, 273, 275]
                       13.11                                [343, 339]
Stratagèmes            15.11                                [549, 108]
Monstres et véhicules  17.03                                [257, 387]
Unités attachées       19.04                           [153, 365, 187]
Appendices des règles  NaN    [251, 391, 392, 176, 261, 379, 277, 411]

Éléments non couverts : 0
Éléments répétés (chevauchement) : 0
================================================================================
[05.04] partie 1/7 · p. 19-19 · 451 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES ÉLÉMENTAIRES > 05 Séquence d'attaque > 05.04 INFLIGER DES DÉGÂTS

Le joueur adverse résout la séquence suivante pour chaque jet de sauvegarde, du résultat le plus bas au plus élevé, jusqu'à avoir résolu toutes les attaques ou avoir détruit toutes les figurines de l'unité ; dans ce dernier cas, les attaques en excès sont perdues.
Choisissez la Figurine : Choisissez 1 figurine dans le groupe d'allocation actuel (voir à droite) ; il doit s'agir d'une figurine qui a perdu un ou plusieurs points de vie si possible.
Vérifiez le Jet de Sauvegarde : Pour chaque résultat, vérifiez si l'attaque inflige des dégâts ou échoue selon la première condition ci-dessous qui s'applique :
Résolvez les Dégâts : Si l'attaque inflige des dégâts, la figurine choisie perd autant de points de vie que la caractéristique de D de l'attaque. Si ceci réduit les points de vie restants de cette figurine à 0 ou moins, elle est détruite.

| -› | non modifié | INFLIGE DES DÉGÂTS |
|------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------|
| -› | Sauvegarde Invulnérable : Les figurines du groupe d'allocation actuel ont une caractéristique de SvIn et le résultat est supérieur ou égal à cette caractéristique. | ÉCHOUE |
| -› | Sauvegarde et PA : Après avoir modifié le résultat avec la caractéristique de PA de l'arme qui attaque, il est supérieur ou égal à la caractéristique de Sv des figurines du groupe d'allocation actuel. | ÉCHOUE |
| | -›Tout autre résultat | INFLIGE DES DÉGÂTS |
================================================================================
[05.04] partie 2/7 · p. 19-20 · 288 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES ÉLÉMENTAIRES > 05 Séquence d'attaque > 05.04 INFLIGER DES DÉGÂTS

### GROUPE D'ALLOCATION ACTUEL
Le premier groupe dans l'ordre d'allocation commence en tant que groupe actuel. Une fois que toutes les figurines d'un groupe d'allocation sont détruites, le groupe suivant dans l'ordre d'allocation devient le groupe actuel.
Exemple : Une caractéristique de PA de -1 modifiera un jet de sauvegarde de 3 en 2. Pour les figurines ayant une caractéristique de Sv de 2+ ou meilleure, cette attaque échouera.

### 1. CHOISIR LES ARMES
L'unité ROUGE attaque. On choisit les armes suivantes avec lesquelles effectuer des attaques :
- 2 bolters (B)
- 2 pistolets bolters (PB)
- 1 bolter lourd (BL)

### 2. CHOISIR LES CIBLES
L'unité BLEUE est choisie comme cible. L'unité est visible de toutes les figurines de l'unité attaquante. Toutes les armes choisies sont à portée, à l'exception d'un pistolet bolter. Par conséquent, cette arme n'effectuera aucune attaque.
================================================================================
[05.04] partie 3/7 · p. 20-21 · 360 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES ÉLÉMENTAIRES > 05 Séquence d'attaque > 05.04 INFLIGER DES DÉGÂTS

### 3. RÉSOUDRE LES ATTAQUES
Il n'y a qu'une seule unité ennemie ciblée, donc le joueur en contrôle rassemble à présent les dés d'attaque :
Cinq dés d'attaque sont rassemblés pour les bolters et le pistolet bolter, qui ont une caractéristique d'A de 2 et 1 respectivement, et effectuent tous des attaques identiques.
Trois dés d'attaque sont rassemblés pour le bolter lourd, qui a une caractéristique d'A de 3 mais n'effectue pas des attaques identiques.

### RÉSOUDRE LES DÉS D'ATTAQUE
-1 au Jet de

### 1. JETS DE TOUCHE
Le joueur en contrôle choisit d'effectuer d'abord cinq jets de touche pour les bolters et pistolet bolter. La caractéristique de CT des armes est de 3+. Quatre des attaques touchent la cible.

### 2. JETS DE BLESSURE
Le joueur en contrôle effectue quatre jets de blessure. Les armes ont une caractéristique de F de 4 et l'unité cible a une caractéristique d'E de 3, il faut donc des jets de 3+ pour blesser. Trois des attaques blessent la cible.

### 3. JETS DE SAUVEGARDE
Le joueur en contrôle de l'unité cible effectue trois jets de sauvegarde.
================================================================================
[15.11] partie 1/2 · p. 55-55 · 549 tokens · regle · renvois ['11.02', '12.04', '15.12']
--------------------------------------------------------------------------------
CHAMPS DE BATAILLE ET TACTIQUES > 15 Stratagèmes > 15.11 INTERVENTION HÉROÏQUE

STRATAGÈME DE BASE
Des cris de guerre montent et vos guerriers se ruent tête baissée face à l'offensive adverse.
EFFET : Résolvez une charge avec votre unité (11.02). Ce faisant, avant de faire le jet de charge, vous devez choisir 1 des modes suivants :
QUAND : À la fin de la phase de Charge adverse. CIBLE : 1 unité non engagée amie à 12" ou moins d'une ou plusieurs unités ennemies. Vous pouvez choisir une unité de VÉHICULE seulement si c'est une unité de PERSONNAGE/MARCHEUR.
Bondir pour Défendre : Quand vous choisissez des cibles de charge, vous pouvez seulement choisir des unités ennemies qui ont effectué un mouvement de charge à cette phase et qui sont dans la distance maximale.
- Dans la Mêlée :
+1PC
Quand vous choisissez des cibles de charge, vous pouvez choisir une ou plusieurs unités ennemies qui sont à 6" ou moins de votre unité et dans la distance maximale.
Quand vous faites le jet de charge, si le résultat est supérieur à 6 (après modificateurs), changez-le par 6.
CONTRE-OFFENSIVE 15.12 2PC STRATAGÈME DE BASE En combat rapproché, la moindre hésitation peut laisser entrevoir une faille à exploiter. Les stratagèmes sont présentés comme ci-dessus. Certains indiquent des conditions optionnelles qui impliquent un coût en PC supplémentaire. Ceci peut dépendre de l'effet choisi (comme dans l'exemple ci-dessus) ou d'autres variables comme les mots-clés de l'unité ciblée.
adverse, juste après qu'une unité ennemie a résolu
QUAND : À l'étape Combattre de la phase de Combat
ses attaques.
CIBLE : 1 unité amie qui est éligible pour combattre.
tude Combat en Premier et elle doit être la prochai-
EFFET : Jusqu'à la fin de la phase, votre unité a l'apti-
ne unité que vous choisissez pour combattre (12.04).
. LA HAINE EST L'ARME LA PLUS FIABLE ++ LÉGENDE DES STRATAGÈMES
Utilisation : Au tour de n'importe quel joueur
57
Utilisation : À votre tour
================================================================================
[15.11] partie 2/2 · p. 57-57 · 108 tokens · regle · renvois []
--------------------------------------------------------------------------------
CHAMPS DE BATAILLE ET TACTIQUES > 15 Stratagèmes > 15.11 INTERVENTION HÉROÏQUE

### STRATAGÈME DE BASE
QUAND : À la fin de la phase de Charge adverse.
CIBLE : 1 unité non engagée amie à 12" ou moins d'une ou plusieurs unités ennemies. Vous pouvez choisir une unité de VÉHICULE seulement si c'est une unité de PERSONNAGE/MARCHEUR.
================================================================================
[02.04] partie 1/1 · p. 10-10 · 292 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES ÉLÉMENTAIRES > 02 Fiches techniques > 02.04 ARMES

Une arme a les caractéristiques suivantes :
Portée (P) : La distance à laquelle l'arme peut tirer. Les armes qui ont une caractéristique de P de 'Mêlée' sont des armes de mêlée.
Attaques (A) : Le nombre de dés d'attaque jetés chaque fois que l'arme est utilisée.
Capacité de Tir (CT) : Présentée comme un résultat de dé (ex. 4+), elle indique la précision du porteur avec l'arme de tir concernée.
Capacité de Combat (CC) : Présentée comme un résultat de dé (ex. 4+), elle reflète le talent du porteur à manier l'arme de mêlée concernée.
Force (F) : Plus la caractéristique de F d'une arme est élevée, plus elle a des chances de blesser un adversaire.
Pénétration d'Armure (PA) : Présentée comme un modificateur à un jet de dé (ex. -1). Plus le modificateur est élevé, plus l'arme a une chance de passer les défenses de la cible.
Dégâts (D) : La quantité de dégâts infligés par une attaque.
================================================================================
[12.03] partie 3/3 · p. 40-40 · 111 tokens · regle · renvois []
--------------------------------------------------------------------------------
LE ROUND DE BATAILLE > 12 Phase de combat > 12.03 MOUVEMENT D'INSERTION

### COMBATS DE DÉBORDEMENT
Quand une unité effectue un combat de débordement, ses figurines peuvent se déplacer de sorte que des unités ennemies qui étaient non engagées deviennent engagées. Ces unités ennemies deviennent éligibles pour combattre à cette phase (et sont même capables de combattre ensuite si ce sont des unités qui Combattent en Premier).
================================================================================
[05.04] partie 1/7 · p. 19-19 · 451 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES ÉLÉMENTAIRES > 05 Séquence d'attaque > 05.04 INFLIGER DES DÉGÂTS

Le joueur adverse résout la séquence suivante pour chaque jet de sauvegarde, du résultat le plus bas au plus élevé, jusqu'à avoir résolu toutes les attaques ou avoir détruit toutes les figurines de l'unité ; dans ce dernier cas, les attaques en excès sont perdues.
Choisissez la Figurine : Choisissez 1 figurine dans le groupe d'allocation actuel (voir à droite) ; il doit s'agir d'une figurine qui a perdu un ou plusieurs points de vie si possible.
Vérifiez le Jet de Sauvegarde : Pour chaque résultat, vérifiez si l'attaque inflige des dégâts ou échoue selon la première condition ci-dessous qui s'applique :
Résolvez les Dégâts : Si l'attaque inflige des dégâts, la figurine choisie perd autant de points de vie que la caractéristique de D de l'attaque. Si ceci réduit les points de vie restants de cette figurine à 0 ou moins, elle est détruite.

| -› | non modifié | INFLIGE DES DÉGÂTS |
|------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------|
| -› | Sauvegarde Invulnérable : Les figurines du groupe d'allocation actuel ont une caractéristique de SvIn et le résultat est supérieur ou égal à cette caractéristique. | ÉCHOUE |
| -› | Sauvegarde et PA : Après avoir modifié le résultat avec la caractéristique de PA de l'arme qui attaque, il est supérieur ou égal à la caractéristique de Sv des figurines du groupe d'allocation actuel. | ÉCHOUE |
| | -›Tout autre résultat | INFLIGE DES DÉGÂTS |
================================================================================
[01.05] partie 1/1 · p. 9-9 · 217 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES ÉLÉMENTAIRES > 01 Concepts de base > 01.05 DÉS

Vous aurez besoin de plusieurs dés à six faces (qu'on abrège souvent en D6). Ces règles font référence à plusieurs jets de dés, comme :
2+, 3+, etc. : 2+ signifie un résultat de 2 ou plus, 3+ signifie un résultat de 3 ou plus, etc.
1-3, 4-6, etc. : Tout résultat inclus dans l'ensemble spécifié interagira avec la règle indiquée.
2D6, 3D6, etc. : Jetez le nombre de D6 indiqué et additionnez les valeurs de chaque dé (ex. pour jeter 2D6, jetez deux D6 et additionnez leurs valeurs respectives).
D3 : Jetez 1 D6 et divisez par deux le résultat (en arrondissant au supérieur).
D6+1, 2D6+3, etc. : Jetez le nombre de dés indiqué et ajoutez la valeur indiquée au résultat.
================================================================================
[24.02] partie 1/1 · p. 78-78 · 411 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÉFÉRENCES > 24 Aptitudes de base > 24.02 APTITUDES DUPLIQUÉES

Plusieurs occurrences de la même aptitude de base ou aptitude d'arme ne se cumulent pas, quels que soient les nombres ou les mots-clés qui y figurent. En pareil cas, le joueur en contrôle doit choisir quelle occurrence il applique à chaque instant donné. Dans le cas d'aptitudes d'arme en plusieurs exemplaires, cette sélection doit être faite à chaque attaque de l'unité, à l'étape Choisir les Armes.
Plusieurs occurrences d'aptitudes de base incluant un nombre comptent comme dupliquées même si ce nombre change. Toutefois, dans le cas d'Éclaireurs, vous devez choisir le nombre le plus bas qui n'est pas partagé par toutes les figurines de l'unité (ex. si toutes les figurines de l'unité ont à la fois Éclaireurs 6" et Éclaireurs 8", vous pouvez choisir Éclaireurs 8" car toutes ses figurines le partagent, mais si une unité contient une figurine avec Éclaireurs 6" et cinq avec Éclaireurs 8", vous devez choisir Éclaireurs 6").
Plusieurs occurrences d'aptitudes d'arme incluant un nombre (ex. [TOUCHES SOUTENUES 1]) comptent comme dupliquées même si ce nombre varie (ex. le joueur en contrôle doit choisir entre [TOUCHES SOUTENUES 1] et [TOUCHES SOUTENUES 2]).
Plusieurs occurrences d'aptitudes d'arme incluant un mot-clé comptent comme dupliquées même si ce motclé change (ex. le joueur en contrôle doit choisir entre [ANTI-VÉHICULE 4+] et [ANTI-INFANTERIE 2+]).
================================================================================
[12.06] partie 1/1 · p. 40-42 · 471 tokens · regle · renvois []
--------------------------------------------------------------------------------
LE ROUND DE BATAILLE > 12 Phase de combat > 12.06 COMBAT DE DÉBORDEMENT

ÉLIGIBLE SI : Votre unité est non engagée, ou l'était au début de l'étape Combattre mais est devenue engagée pendant la phase de Combat.
EFFET : Votre unité peut faire 1 mouvement d'insertion supplémentaire, puis elle combat comme décrit dans Effectuer des Attaques (04).

### COMBAT NORMAL
Les joueurs choisissent à tour de rôle des unités pour combattre. Les unités qui Combattent en Premier doivent être choisies avant toute autre unité éligible.
1. Le joueur ROUGE choisit son MONSTRE pour combattre. Il effectue un combat normal, et détruit le TRANSPORT.
L'unité embarquée effectue un mouvement de débarquement d'urgence. Après cela, elle est non engagée.
Unité qui Combat en Premier
Unité qui Combat en Premier

### COMBAT DE DÉBORDEMENT
3. Le joueur BLEU n'a pas d'unité qui Combat en Premier, donc le joueur ROUGE choisit son unité suivante.
Le joueur ROUGE choisit une autre unité qui Combat en Premier. Cette unité est non engagée, mais était engagée avec le TRANSPORT au début de l'étape Combattre, et peut donc faire un combat de débordement. Elle effectue d'abord un mouvement d'insertion pour engager l'unité qui a débarqué, puis combat, et détruit deux figurines ennemies.
5. L'unité du joueur BLEU combat en représailles, mais n'inflige aucun dégât.

### DE NOUVEAUX ADVERSAIRES
À AFFRONTER En utilisant le mode consolidation d'engagement, votre unité peut finir son mouvement de consolidation engagée avec des unités ennemies qu'elle n'avait pas encore combattues à cette phase. Dans ce cas, chacune de ces unités ennemies aura une opportunité de combattre votre unité, alors réfléchissez soigneusement au niveau d'agressivité que vous voulez donner au déplacement de votre unité avec ce mode.
================================================================================
[15.08] partie 1/1 · p. 57-57 · 101 tokens · regle · renvois []
--------------------------------------------------------------------------------
CHAMPS DE BATAILLE ET TACTIQUES > 15 Stratagèmes > 15.08 TIR EN ÉTAT D'ALERTE

### STRATAGÈME DE BASE
QUAND : À la fin de la phase de
Mouvement adverse.
CIBLE : 1 unité non engagée amie (sauf les unités TITANESQUES).
EFFET : Votre unité tire en utilisant le type tir au jugé (voir ci-dessous).
================================================================================
[nan] partie 1/1 · p. 62-62 · 68 tokens · regle · renvois []
--------------------------------------------------------------------------------
RÈGLES AVANCÉES > 17 Monstres et véhicules

En raison de leur taille imposante et de leur nature implacable, les Monstres et les Véhicules fonctionnent différemment sur le champ de bataille. Cette section détaille les règles supplémentaires requises pour utiliser ces unités.
================================================================================
[13.03] partie 1/1 · p. 46-46 · 68 tokens · regle · renvois []
--------------------------------------------------------------------------------
CHAMPS DE BATAILLE ET TACTIQUES > 13 Terrain > 13.03 EXPOSÉ

Le terrain exposé offre une maigre protection aux troupes les plus désespérées, et peut être franchi sans encombre. Exemples : Cratères, barbelés, débris épars.
================================================================================
[18.04] partie 1/1 · p. 65-65 · 492 tokens · regle · renvois ['03.02']
--------------------------------------------------------------------------------
RÈGLES AVANCÉES > 18 Transport > 18.04 MOUVEMENT DE DÉBARQUEMENT

DISTANCE DE PLACEMENT :
Débarquement Rapide/Tactique : 3"
Débarquement de Combat : 6"
ÉLIGIBLE SI : Tous les points suivants s'appliquent à votre unité :
Embarquée dans une figurine de TRANSPORT qui est sur le champ de bataille.
- N'a pas embarqué dans le TRANSPORT à cette phase.
Le TRANSPORT n'a pas effectué de mouvement d'avance ni de retraite à cette phase.
EFFET : Votre unité est placée comme décrit dans Placement (03.02).
AVANT DE SE DÉPLACER : Choisissez le mode de débarquement :
-› Débarquement Rapide : Si le TRANSPORT a fait un mouvement normal ou d'arrivée à cette phase, vous devez choisir ce mode.
-› Débarquement Tactique : Sinon, si le TRANSPORT est resté immobile ou n'a pas encore été choisi pour se déplacer à cette phase, si vous pouvez placer votre unité comme décrit ci-dessous, vous devez choisir ce mode.
-› Débarquement de Combat : Sinon, vous devez choisir ce mode. Faites un jet de risque pour chaque figurine de votre unité.
EN SE DÉPLAÇANT : Placez chaque figurine de votre unité
entièrement dans la distance de placement du TRANSPORT.
Débarquement Rapide : Si le TRANSPORT a fait un mouvement d'arrivée à ce tour, chaque figurine doit suivre les mêmes règles que le TRANSPORT devait suivre en résolvant ce mouvement.
Débarquement de Combat : Chaque figurine peut être placée engagée avec une ou plusieurs unités ennemies avec lesquelles le TRANSPORT est engagé.
APRÈS D'ÊTRE DÉPLACÉ :
Débarquement Rapide : Jusqu'à la fin du tour, votre unité n'est pas éligible pour déclarer une charge.
Débarquement Tactique : Choisissez votre unité pour effectuer un mouvement normal ou d'avance.
Débarquement de Combat : Votre unité est ébranlée et, jusqu'à la fin du tour, elle n'est pas éligible pour déclarer une charge.

In [ ]:
df_chunks